<section class="conta">
    <?php foreach($this->view->dados as $dados){?>
        <div class="info">
            <span>Titular : <?php echo $dados['nome']?></span>
            <span>Conta : <?php echo $dados['numero']?></span>
        </div>
    <div class="saldo">
        <h1>Saldo: R$ <?php echo $dados['saldo']?></h1>
    </div>
    <?php } ?>

    <div class="acoes-link">
        <a href="?acao=sacar">Saque</a>
        <br><br>
        <a href="?acao=depositar">Depósito</a>
    </div>
    
    <?php if(isset($_GET['acao'])){?>
        <div class="acoes">
            
            <?php if($_GET['acao'] === 'sacar'){ ?>
                <form action="?acao=sacar" method="POST">
                <label>Digite o valor a ser retirado</label>
            <?php }elseif($_GET['acao'] === 'depositar'){ ?>
                <form action="?acao=depositar" method="POST">
                <label>Digite o valor a ser depositado</label>
            <?php } ?>
                <br><input type="text" name="valor"><br><br>
                <button type="submit">Confirmar</button>
            </form>
            <?php if(isset($this->view->msg)){?>
                <h4><?php echo $this->view->msg ?></h4>
            <?php } ?>
            <a href="/">Cancelar</a>
        </div>
    <?php } ?>
</section>

<footer>
    <a style="color:black"href="/logout">Sair</a>
</footer>
